
FROM ://microsoft.com AS build-env
WORKDIR /app


COPY GanttManager.API/*.csproj ./GanttManager.API/
RUN dotnet restore ./GanttManager.API/GanttManager.API.csproj


COPY GanttManager.API/ ./GanttManager.API/


WORKDIR /app/GanttManager.API
RUN dotnet publish -c Release -o /app/out


FROM ://microsoft.com
WORKDIR /app
COPY --from=build-env /app/out .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "GanttManager.API.dll"]
