version: '3.8'

services:
  gantt_db:
    image: postgres:15-alpine
    container_name: gantt_postgresql
    environment:
      POSTGRES_USER: hacaton_user
      POSTGRES_PASSWORD: SecretPassword123
      POSTGRES_DB: gantt_project_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
